apiVersion: v1
kind: Service
metadata:
  name: external-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-svc
subsets:
  - addresses:
      - ip: 35.221.67.40
    ports:
      - port: 8080