kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: microservice-a
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: microservice-a
  name: deployment-editor
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: microservice-a
subjects:
- kind: Group
  name: dev@samuraitaiga.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-editor-binding
  namespace: microservice-a
subjects:
- kind: Group
  name: sre@samuraitaiga.io
roleRef:
  kind: Role
  name: deployment-editor
  apiGroup: rbac.authorization.k8s.io